connector:
  name: 'Project Github Connector '
  identifier: Project_Github_Connector
  description:
  orgIdentifier: KD
  projectIdentifier: Fresh_GitX
  type: Github
  spec:
    url: https://github.com/KapilDigani
    validationRepo: test
    authentication:
      type: Http
      spec:
        type: UsernameToken
        spec:
          username: KapilDigani
          tokenRef: KD_Github
    apiAccess:
      type: Token
      spec:
        tokenRef: KD_Github_PAT
    executeOnDelegate: false
    type: Account
